stages:
  - build
  - lint
  - test

composer-install:
  stage: build
  image: php:8.5-cli
  variables:
    DOCKER_PULL_POLICY: always
  before_script:
    - apt-get update -q && apt-get install -y libpq-dev zip unzip git
    - docker-php-ext-install pdo pdo_pgsql
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install --prefer-dist --no-interaction --no-progress --no-scripts --ignore-platform-req=ext-intl --ignore-platform-req=ext-exif
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor/
      - .composer/cache
    policy: pull-push
  artifacts:
    paths:
      - vendor/
    expire_in: 1h

pint:
  stage: lint
  image: php:8.5-cli
  needs: ["composer-install"]
  script:
    - ./vendor/bin/pint --test

phpstan:
  stage: lint
  image: php:8.5-cli
  needs: ["composer-install"]
  script:
    - ./vendor/bin/phpstan analyse --memory-limit=512M --error-format gitlab > phpstan-report.json
  artifacts:
    when: always
    reports:
      codequality: phpstan-report.json

phpunit:
  stage: test
  image: php:8.5-cli
  needs: ["composer-install"]
  before_script:
    - apt-get update -q && apt-get install -y libpq-dev
    - docker-php-ext-install pdo pdo_pgsql

  services:
    - name: postgres:18-alpine
      alias: pgsql

  variables:
    POSTGRES_DB: testing
    POSTGRES_USER: sail
    POSTGRES_PASSWORD: password
    DB_CONNECTION: pgsql
    DB_HOST: pgsql
    DB_PORT: 5432
    DB_DATABASE: testing
    DB_USERNAME: sail
    DB_PASSWORD: password
    APP_ENV: testing

  script:
    - php artisan test
