stages:
  - build
  - lint
  - test

composer-install:
  stage: build
  image: php:8.5-cli
  variables:
    DOCKER_PULL_POLICY: always
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install --prefer-dist --no-interaction --no-progress --no-scripts --ignore-platform-reqs
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor/
      - .composer/cache
    policy: pull-push
  artifacts:
    paths:
      - vendor/
    expire_in: 1h

pint:
  stage: lint
  image: php:8.5-cli
  needs: ["composer-install"]
  script:
    - ./vendor/bin/pint --test

phpstan:
  stage: lint
  image: php:8.5-cli
  needs: ["composer-install"]
  script:
    - ./vendor/bin/phpstan analyse --memory-limit=512M --error-format gitlab > phpstan-report.json
  artifacts:
    when: always
    reports:
      codequality: phpstan-report.json

phpunit:
  stage: test
  image: php:8.5-cli
  needs: ["composer-install"]
  before_script:
    - apt-get update -q && apt-get install -y libpq-dev
    - docker-php-ext-install pdo pdo_pgsql
    - pecl install xdebug && docker-php-ext-enable xdebug

  services:
    - name: postgres:18-alpine
      alias: pgsql

  variables:
    POSTGRES_DB: testing
    POSTGRES_USER: sail
    POSTGRES_PASSWORD: password
    DB_CONNECTION: pgsql
    DB_HOST: pgsql
    DB_PORT: 5432
    DB_DATABASE: testing
    DB_USERNAME: sail
    DB_PASSWORD: password
    APP_ENV: testing
    XDEBUG_MODE: coverage

  script:
    - ./vendor/bin/phpunit --coverage-text --colors=never --coverage-html coverage --coverage-cobertura=coverage.cobertura.xml

  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 1 day
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml